// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEb-U3Mu3LQxOsqe6GDn5hwy7cv_c9Mrc',
    appId: '1:944201480072:web:798fb543c6670d7babec3d',
    messagingSenderId: '944201480072',
    projectId: 'newbigmart-d0790',
    authDomain: 'newbigmart-d0790.firebaseapp.com',
    storageBucket: 'newbigmart-d0790.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72QuxJOENUY_ETFXrGuhpp8Y3452SkNQ',
    appId: '1:944201480072:android:e6c5b8b09a0c9982abec3d',
    messagingSenderId: '944201480072',
    projectId: 'newbigmart-d0790',
    storageBucket: 'newbigmart-d0790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLYLZ-bnKcZnAeoPpmCCZQE9DjubWOquo',
    appId: '1:944201480072:ios:e1664a87898d2390abec3d',
    messagingSenderId: '944201480072',
    projectId: 'newbigmart-d0790',
    storageBucket: 'newbigmart-d0790.appspot.com',
    iosBundleId: 'com.example.newbigmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLYLZ-bnKcZnAeoPpmCCZQE9DjubWOquo',
    appId: '1:944201480072:ios:bec799b7d8d751f3abec3d',
    messagingSenderId: '944201480072',
    projectId: 'newbigmart-d0790',
    storageBucket: 'newbigmart-d0790.appspot.com',
    iosBundleId: 'com.example.newbigmart.RunnerTests',
  );
}
